### ISSUE TITLE
QC flags

### ISSUE THREAD

**Issue by fa2k** [nsc-norway/lims#13]
NovaSeq protocol doesn't have QC flag, and closes the step when the run is complete. We can determine how to handle QC of novaseq runs.

**Comment by ghost** [comment]
We can add a Data QC step after the NovaSeq run step and set it to complete automatically. Can test if it works by manually posting run status using the API. There's no need to check with support, because it is a small change to undo it, and if there's trouble we can come up with a different solution to start the next step (cron job).

Overview page must be updated to show both NovaSeq Run steps and NovaSeq Data QC steps in the same column. (Same change can be used to also display HiSeq X and HiSeq 4000 in same column)

**Comment by ghost** [comment]
Data QC Step added a while ago and working brilliantly
